ICONS = {
    "folder": "📁",
    "binary": "📦",
    "archive": "📦",
    "script": "📜",
    "text": "📄",
    "code": "💻",
    "gear": "⚙️",
    "link": "🔗",
    "computer": "🖥️",
    "house": "🏠",
    "network": "🖧",
    "lock": "🔒",
    "cloud": "☁️",
    "local": "💻",
    "sunrise": "🌅",
    "sunrise over mountains": "🌄",
    "rainbow": "🌈",
    "star": "⭐",
    "rocket": "🚀",
    "alien": "👽",
    "ghost": "👻",
    "fire": "🔥",
    "sparkles": "✨",
    "heart": "❤️",
    "magnifying glass": "🔍",
    "wrench": "🔧",
    "document": "📃",
    "clipboard": "📋",
    "trash": "🗑️",
    "snake": "🐍",
    "musical note": "🎵",
    "camera": "📷",
    "dvd": "📀",
    "joypad": "🎮",
    "book": "📚",
    "light bulb": "💡",
    "bell": "🔔",
    "envelope": "✉️",
    "joystick": "🕹️",
    "radio": "📻",
    "radioactive": "☢️",
    "biohazard": "☣️",
    "danger": "⚠️",
    "check mark": "✔️",
    "automobile": "🚗",
    "clover": "☘️",
    "bar chart": "📊",
    "chart up": "📈",
    "package": "📦",
    "key": "🔑",
    "paperclip": "📎",
    "cabinet": "🗄️",
    "raised hand": "✋",
    "thumbs up": "👍",
    "globe": "🌍",
    "picture": "🖼️",
    "art": "🎨",
    "video": "🎬",
}
